### ISSUE TITLE
TSC Frequency not probed correctly

### ISSUE THREAD

**Issue by danfruehauf** [andre-richter/pcie-lat#2]
On a server I'm running this utility on, I encounter unreasonable clock frequencies.

For example:
```
TSC freq:     1034704.0 Hz
TSC overhead: 27 cycles
```

The clock frequency is actually 5GHz. This yields unlikely PCIe latency results, like:
```
       | Results (1000 samples)
------------------------------------------------------
Mean   |  11218.96 cycles | 10842679.65 ns
Stdd   |    390.80 cycles | 377693.83 ns
```

**Comment by andre-richter** [comment]
Disclaimer: I haven't used this tool in a long time.

The TSC frequency in this case is probed by the Linux kernel directly. My driver [just uses](https://github.com/andre-richter/pcie-lat/blob/master/pcie-lat.c#L595) the symbol `tsc_khz` that Linux is exporting.

Unless something goes wrong when the ruby script queries it, I think you need to check the kernel 🤔

**Comment by andre-richter** [comment]
Closing. #3 most likely fixed this.
